stages:
  - analysis
  - test

variables:
  COMPOSER_NO_INTERACTION: "1"

.php-setup:
  image: php:8.4-cli
  before_script:
    - apt-get update -qq && apt-get install -yqq git unzip libzip-dev
    - docker-php-ext-install zip pdo pdo_mysql
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-progress

phpstan:
  extends: .php-setup
  stage: analysis
  script:
    - vendor/bin/phpstan analyse

phpcs:
  extends: .php-setup
  stage: analysis
  script:
    - vendor/bin/phpcs

phpunit:
  extends: .php-setup
  stage: test
  script:
    - vendor/bin/phpunit
