<?php

declare(strict_types=1);

namespace MarekSkopal\ORM\Schema\Compiler;

use MarekSkopal\ORM\Schema\ColumnSchema;
use MarekSkopal\ORM\Schema\EntitySchema;
use MarekSkopal\ORM\Schema\Provider\SchemaProvider;
use MarekSkopal\ORM\Schema\Schema;
use ReflectionClass;

/**
 * Renders a schema, including the generated hydrators and extractors, as a PHP file that returns
 * the Schema. Loaded through opcache, the file needs no attribute scan, reflection or code generation.
 */
final class SchemaDumper
{
    public function dump(Schema $schema): string
    {
        $schemaProvider = new SchemaProvider($schema);
        $hydratorGenerator = new HydratorGenerator($schemaProvider);
        $extractorGenerator = new ExtractorGenerator($schemaProvider);
        $normalizerGenerator = new NormalizerGenerator($hydratorGenerator, $extractorGenerator);

        $entities = [];
        foreach ($schema->entities as $entityClass => $entitySchema) {
            // Each entity schema is built on first use, so loading the file stays cheap however many entities it holds.
            $entities[] = CodeExporter::value($entityClass) . ' => ' . CodeExporter::className(EntitySchema::class)
                . '::lazy(static fn(): ' . CodeExporter::className(EntitySchema::class) . ' => ' . $this->entitySchema(
                    $entitySchema,
                    $hydratorGenerator->generate($entitySchema),
                    $extractorGenerator->generate($entitySchema),
                    $normalizerGenerator->generate($entitySchema),
                ) . ')';
        }

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by marekskopal/orm. Do not edit; regenerate with SchemaBuilder::dump().\n\nreturn new "
            . CodeExporter::className(Schema::class) . "([\n" . implode(",\n", $entities) . ",\n]);\n";
    }

    private function entitySchema(EntitySchema $entitySchema, string $hydrator, string $extractor, string $normalizer): string
    {
        $columns = [];
        foreach ($entitySchema->columns as $propertyName => $columnSchema) {
            $columns[] = '        ' . CodeExporter::value($propertyName) . ' => ' . $this->columnSchema($columnSchema) . ',';
        }

        return 'new ' . CodeExporter::className(EntitySchema::class) . "(\n"
            . '    entityClass: ' . CodeExporter::value($entitySchema->entityClass) . ",\n"
            . '    repositoryClass: ' . CodeExporter::value($entitySchema->repositoryClass) . ",\n"
            . '    table: ' . CodeExporter::value($entitySchema->table) . ",\n"
            . '    tableAlias: ' . CodeExporter::value($entitySchema->tableAlias) . ",\n"
            . "    columns: [\n" . implode("\n", $columns) . "\n    ],\n"
            . '    hydrator: ' . $this->indent($hydrator) . ",\n"
            . '    extractor: ' . $this->indent($extractor) . ",\n"
            . '    normalizer: ' . $this->indent($normalizer) . ",\n"
            . ')';
    }

    /** Exports only the constructor arguments that differ from their defaults. */
    private function columnSchema(ColumnSchema $columnSchema): string
    {
        $values = get_object_vars($columnSchema);
        $arguments = [];
        foreach (new ReflectionClass(ColumnSchema::class)->getConstructor()?->getParameters() ?? [] as $parameter) {
            $name = $parameter->getName();
            $value = $values[$name];
            if ($parameter->isDefaultValueAvailable() && $parameter->getDefaultValue() === $value) {
                continue;
            }

            $arguments[] = $name . ': ' . CodeExporter::value($value);
        }

        return 'new ' . CodeExporter::className(ColumnSchema::class) . '(' . implode(', ', $arguments) . ')';
    }

    private function indent(string $code): string
    {
        return str_replace("\n", "\n    ", $code);
    }
}
